// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: ticker.proto

package ticker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TickerService_Subscribe_FullMethodName   = "/ticker.TickerService/Subscribe"
	TickerService_UnSubscribe_FullMethodName = "/ticker.TickerService/UnSubscribe"
)

// TickerServiceClient is the client API for TickerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerServiceClient interface {
	Subscribe(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*TickerAck, error)
	UnSubscribe(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*TickerAck, error)
}

type tickerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerServiceClient(cc grpc.ClientConnInterface) TickerServiceClient {
	return &tickerServiceClient{cc}
}

func (c *tickerServiceClient) Subscribe(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*TickerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TickerAck)
	err := c.cc.Invoke(ctx, TickerService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerServiceClient) UnSubscribe(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*TickerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TickerAck)
	err := c.cc.Invoke(ctx, TickerService_UnSubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerServiceServer is the server API for TickerService service.
// All implementations must embed UnimplementedTickerServiceServer
// for forward compatibility.
type TickerServiceServer interface {
	Subscribe(context.Context, *TickerRequest) (*TickerAck, error)
	UnSubscribe(context.Context, *TickerRequest) (*TickerAck, error)
	mustEmbedUnimplementedTickerServiceServer()
}

// UnimplementedTickerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTickerServiceServer struct{}

func (UnimplementedTickerServiceServer) Subscribe(context.Context, *TickerRequest) (*TickerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTickerServiceServer) UnSubscribe(context.Context, *TickerRequest) (*TickerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnSubscribe not implemented")
}
func (UnimplementedTickerServiceServer) mustEmbedUnimplementedTickerServiceServer() {}
func (UnimplementedTickerServiceServer) testEmbeddedByValue()                       {}

// UnsafeTickerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerServiceServer will
// result in compilation errors.
type UnsafeTickerServiceServer interface {
	mustEmbedUnimplementedTickerServiceServer()
}

func RegisterTickerServiceServer(s grpc.ServiceRegistrar, srv TickerServiceServer) {
	// If the following call pancis, it indicates UnimplementedTickerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TickerService_ServiceDesc, srv)
}

func _TickerService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TickerService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerServiceServer).Subscribe(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerService_UnSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerServiceServer).UnSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TickerService_UnSubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerServiceServer).UnSubscribe(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerService_ServiceDesc is the grpc.ServiceDesc for TickerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticker.TickerService",
	HandlerType: (*TickerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _TickerService_Subscribe_Handler,
		},
		{
			MethodName: "UnSubscribe",
			Handler:    _TickerService_UnSubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticker.proto",
}
